In [11]:
import numpy as np

from connect4.board import Piece

grid = np.full((6, 7), Piece(' '), dtype=Piece)

def add_piece(grid, row, col, piece: Piece) -> None:
    grid[row,col] = piece

piece = Piece('Y')

In [12]:
%%timeit
add_piece(grid, 3, 4, piece)

741 ns ± 57.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
from enum import Enum, auto

class Piece2(Enum):
    EMPTY = auto()
    RED = auto()
    YELLOW = auto()

grid = np.full((6, 7), Piece2(Piece2.EMPTY), dtype=Piece)

def add_piece(grid, row, col, piece: Piece2) -> None:
    grid[row,col] = piece

piece = Piece2(Piece2.RED)

In [17]:
%%timeit
add_piece(grid, 3, 4, piece)

624 ns ± 76.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [247]:
def _is_diagonal_winner(pos, player_pieces: np.ndarray) -> bool:
        """Checks if player_pieces contains a vertical or horizontal win."""
        r, c  = pos
        L = 4
        C, R = 7-1, 6-1
        topleft = min(r,c)
        bottomright = min(R-r,C-c)
        topright = min(r,C-c)
        bottomleft = min(R-r,c)
        #topleft = min(r,c)-1
        #bottomright = min(R-r,C-c)
        #topright = min(r-1,C-c)
        #bottomleft = min(R-r,c-1)
        print(topleft,bottomright,topright,bottomleft)
        #rng1 = range(min(L-1,topleft), max(0,L-bottomright-1)-1,-1)
        #rng2 = range(min(L-1,bottomleft), max(0,L-topright-1)-1,-1)
        rng1 = range(min(L-1,topleft), max(0,L-bottomright-1)-1,-1)
        rng2 = range(min(L-1,bottomleft), max(0,L-topright-1)-1,-1)
        rng1 = range(max(0,L-bottomright-1),min(L-1,topleft)+1)
        rng2 = range(max(0,L-topright-1),min(L-1,bottomleft)+1)
        print(rng1)
        for i in rng1:
            print([(r - i + x, c - i + x) for x in range(L)])
            #if all(player_pieces[r + i + x -1][c + i + x -1] for x in range(L)):
            #        return True
        print(rng2)
        for i in rng2:
            print([(r + i - x, c - i + x) for x in range(L)])
            #if all(player_pieces[r - i - x -1][c + i + x -1] for x in range(L)):
            #        return True

In [248]:
b = np.zeros((6,7),dtype=int)

pos = (3,3)

r, c  = pos
#idx = tuple(x-1 for x in pos)
#b[idx] = 1
b[pos] =1

_is_diagonal_winner(pos, b)

print(b)

3 2 3 2
range(1, 4)
[(2, 2), (3, 3), (4, 4), (5, 5)]
[(1, 1), (2, 2), (3, 3), (4, 4)]
[(0, 0), (1, 1), (2, 2), (3, 3)]
range(0, 3)
[(3, 3), (2, 4), (1, 5), (0, 6)]
[(4, 2), (3, 3), (2, 4), (1, 5)]
[(5, 1), (4, 2), (3, 3), (2, 4)]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [67]:
L = 4
C, R = 7, 6
topleft = min(L-1,r,c)
bottomright = min(L-1,R-r,C-c)
topright = min(L-1,r,C-c)
bottomleft = min(L-1,R-r,c)
print(topleft,bottomleft,bottomright,topright)
range(-topleft, bottomright-L)

3 2 2 2


range(-3, -2)