In [11]:
import numpy as np

from connect4.board import Piece

grid = np.full((6, 7), Piece(' '), dtype=Piece)

def add_piece(grid, row, col, piece: Piece) -> None:
    grid[row,col] = piece

piece = Piece('Y')

In [12]:
%%timeit
add_piece(grid, 3, 4, piece)

741 ns ± 57.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
from enum import Enum, auto

class Piece2(Enum):
    EMPTY = auto()
    RED = auto()
    YELLOW = auto()

grid = np.full((6, 7), Piece2(Piece2.EMPTY), dtype=Piece)

def add_piece(grid, row, col, piece: Piece2) -> None:
    grid[row,col] = piece

piece = Piece2(Piece2.RED)

In [17]:
%%timeit
add_piece(grid, 3, 4, piece)

624 ns ± 76.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [88]:
def _is_diagonal_winner(pos, player_pieces: np.ndarray) -> bool:
        """Checks if player_pieces contains a vertical or horizontal win."""
        r, c  = pos
        L = 4
        C, R = 7, 6
        topleft = min(r,c)
        bottomright = min(R-r,C-c)
        topright = min(r,C-c)
        bottomleft = min(R-r,c)
        for i in range(-min(L,bottomleft),min(0,topright-L)):
            print([(r + i + x, c + i + x) for x in range(L)])
            #if all(player_pieces[r + i + x -1][c + i + x -1] for x in range(L)):
            #        return True
        for i in range(-min(L,topleft+1), min(0,bottomright-L+1)):
            print([(r + i + x, c - i - x) for x in range(L)])
            #if all(player_pieces[r - i - x -1][c + i + x -1] for x in range(L)):
            #        return True

In [89]:
b = np.zeros((6,7),dtype=int)

pos = (2,3)
r, c  = pos
idx = tuple(x-1 for x in pos)
b[idx] = 1

_is_diagonal_winner(pos, b)

print(b)

[(-1, 0), (0, 1), (1, 2), (2, 3)]
[(1, 4), (2, 3), (3, 2), (4, 1)]
[(2, 3), (3, 2), (4, 1), (5, 0)]
[[0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [67]:
L = 4
C, R = 7, 6
topleft = min(L-1,r,c)
bottomright = min(L-1,R-r,C-c)
topright = min(L-1,r,C-c)
bottomleft = min(L-1,R-r,c)
print(topleft,bottomleft,bottomright,topright)
range(-topleft, bottomright-L)

3 2 2 2


range(-3, -2)